# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake graph (modifica o test alternativo)
      - name: Generate Snake
        run: |
          curl -o snake.svg "https://platane.github.io/snk/api?username=Enrico-github"
          mkdir -p dist
          mv snake.svg dist/

      # Commit and push changes
      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Update snake contribution graph" || echo "No changes to commit"
          git push origin output --force

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: output
          folder: dist
